server:
  port: 8080

# mysql
spring:
  datasource:
    url: jdbc:mysql://133.64.27.29:8803/paas?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Gxroot_set_1617188801

  servlet:
    multipart:
      max-request-size: 10485760
      max-file-size: 10485760

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ffcs.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
